repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.3
    hooks:
      - id: flake8
        exclude: ^app/migrations/
        args: [--max-line-length=120]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--line-length=120]
